daemon: yes
ds:
  exe_path: /il2ds/il2server.exe
api:
  http:
    bind:
      address: 0.0.0.0
      port: 5000
logging:
  trace: no
  files:
    main:
      file_path: /var/log/airbridge/main.log
      level: info
    exceptions:
      file_path: /var/log/airbridge/exceptions.log
